In [23]:
import numpy as np
def Atan(y,x):
    if x==0 and y==0:
        print("angle is not defined")
        return None
    elif x==0:
        return np.sign(y)*np.pi/2
    else:
        angle=np.arctan(y/x)
        if x<0 and y>0:
            return np.pi+angle
        elif x<0 and y<0:
            return -np.pi+angle
        else:
            return angle

In [28]:
d1=1
d2=1
R=np.array([[1, 0, 0],
            [0, 0, -1],
            [0, 1, 0]])
O=np.array([1.1, 0, 1])

In [33]:
ox,oy,oz=O
q1=Atan(oy,ox)
r=np.sqrt(ox**2+oy**2)
s=oz-d1
q2=Atan(s,r)
d3=np.sqrt(s**2+r**2)-d2

print("q1 =",q1)
print("q2 =",q2)
print("d3 =",d3)

q1 = 0.0
q2 = 0.0
d3 = 0.10000000000000009


In [36]:
n=3
dh=np.array([[q1, d1, 0, np.pi/2],
             [q2, 0, d2, 0],
             [0, 0, d3, 0]])

A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])
ans=np.identity(4)

for i in range(n):
    ans=ans@A[i]
print("position of end effector:", np.around(ans[0:3,3],5))
print("orientation of end effector:")
print(np.around(ans[0:3,0:3],5))

position of end effector: [1.1 0.  1. ]
orientation of end effector:
[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
