In [207]:
import numpy as np

In [208]:
def Atan(y,x):
    if x==0 and y==0:
        print("angle is not defined")
        return None
    elif x==0:
        return np.sign(y)*np.pi/2
    else:
        angle=np.arctan(y/x)
        if x<0 and y>0:
            return np.pi+angle
        elif x<0 and y<0:
            return -np.pi+angle
        else:
            return angle
            

In [210]:
d1=1
d2=1
d6=0.1
R=np.array([[1, 0, 0],
            [0, 1, 0],
            [0, 0, 1]])
O=np.array([2, 0, 1.1])

Pc=np.array([O[0]-d6*R[0][2], O[1]-d6*R[1][2], O[2]-d6*R[2][2]])
# print(Pc)

In [211]:
xc,yc,zc=Pc
if xc==0:
    q1=np.pi/2
else:
    q1=Atan(yc,xc)

r=np.sqrt(xc**2+yc**2)
d=np.sqrt((zc-d1)**2+r**2)-d2

if r==0:
    q2=np.pi/2
else:
    q2=Atan(zc-d1,r)

In [212]:
R01=np.array([[np.cos(q1), -np.sin(q1), 0],
              [np.sin(q1), np.cos(q1), 0],
              [0, 0, 1]])
# R12=np.array([[np.cos(q2), -np.sin(q2), 0],
#               [np.sin(q2), np.cos(q2), 0],
#               [0, 0, 1]])
R12=np.array([[np.cos(-q2), 0, np.sin(-q2)],
              [0, 1, 0],
              [-np.sin(-q2), 0, np.cos(-q2)]])
R23=np.array([[np.cos(np.pi/2), 0, np.sin(np.pi/2)],
              [0, 1, 0],
              [-np.sin(np.pi/2), 0, np.cos(np.pi/2)]])
R03=R01@R12@R23
# q2=-q2
# n=3
# dh=np.array([[q1, d1, 0, np.pi/2],
#              [q2, d2, 0, np.pi/2],
#              [0, d, 0, 0]])
# A=[0]*n
# for i in range(n):
#     theta, d, a, alpha = dh[i]
#     A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
#                    [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
#                    [0, np.sin(alpha), np.cos(alpha), d],
#                    [0, 0, 0, 1]])
# ans=np.identity(4)

# for i in range(n):
#     ans=ans@A[i]
# R03=ans[0:3,0:3]   
# print(ans)
R36=R03.T@R

if R36[0][2]==0 and R36[1][2]==0:
    q4=0
else:
    q4=Atan(np.sqrt(1-R36[2][2]**2), R36[2][2])
    
if q4==0:
    q5=0
else:
    q5=Atan(R36[2][1]/np.sin(q4), -R36[2][0]/np.sin(q4))

A=np.cos(q4)*np.cos(q5)
B=np.sin(q5)
sine=(-B*R36[0][0]+A*R36[1][0])/(A**2+B**2)
cosine=(A*R36[0][0]+B*R36[1][0])/(A**2+B**2)
q3=Atan(sine,cosine)

In [213]:
q1,q2,d,q3,q4,q5

(0.0, 0.0, 1.0, 0.0, 1.5707963267948966, -0.0)

Testing the joint parameters using forwards kinematics.

In [206]:
n=3
# dh=np.array([[q1, d1, 0, -np.pi/2],
#              [q2, d2, 0, np.pi/2],
#              [0, d, 0, 0],
#              [q3, 0, 0, -np.pi/2],
#              [q4, 0, 0, np.pi/2],
#              [q5, d6, 0, 0]])

dh=np.array([[q1, d1, 0, np.pi/2],
             [np.pi/2-q2, 0, 0, -np.pi/2],
             [0, 0, d+d2, 0]])
A=[0]*n
for i in range(n):
    theta, d_dh, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d_dh],
                   [0, 0, 0, 1]])
ans=np.identity(4)

for i in range(n):
    ans=ans@A[i]
print("position of end effector:", ans[0:3,3])
print("orientation of end effector:")
print(np.around(R03))
print(np.around(ans[0:3,0:3]))

# np.array([ans[0:3,3]]).T
# print(ans[0:3,0:3])
# print(R03)

position of end effector: [1.2246468e-16 1.2246468e-16 3.0000000e+00]
orientation of end effector:
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
[[ 0. -0. -1.]
 [ 0.  1. -0.]
 [ 1. -0.  0.]]


In [13]:
r1=np.array([[np.cos(q3), -np.sin(q3), 0],
             [np.sin(q3), np.cos(q3), 0],
             [0, 0, 1]])
r2=np.array([[np.cos(q4), 0, np.sin(q4)],
             [0, 1, 0],
             [-np.sin(q4), 0, np.cos(q4)]])
r3=np.array([[np.cos(q5), -np.sin(q5), 0],
             [np.sin(q5), np.cos(q5), 0],
             [0, 0, 1]])
(r1@r2@r3)

array([[ 0.99875234, -0.04993762,  0.        ],
       [ 0.04993762,  0.99875234,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [16]:
np.around(R03@R36),A,B

(array([[1., 0., 0.],
        [0., 1., 1.],
        [0., 0., 1.]]),
 1.0,
 0.0)

In [25]:
a=Atan2(0,0)

angle is not defined


In [63]:
np.arctan(1/2)/np.pi*180

26.565051177077986

In [69]:
Atan2(1,2)/np.pi*180

26.565051177077986

In [38]:
np.array(ans[0:3,3]).T

array([1., 0., 1.])