In [52]:
import numpy as np
def Atan(y,x):
    if x==0 and y==0:
        print("angle is not defined. Returning 0")
        return 0
    elif x==0:
        return np.sign(y)*np.pi/2
    else:
        angle=np.arctan(y/x)
        if x<0 and y>0:
            return np.pi+angle
        elif x<0 and y<0:
            return -np.pi+angle
        else:
            return angle

In [87]:
d1=1
d2=1
d4=1
R=np.array([[1, 0, 0],
            [0, -1, 0],
            [0, 0, -1]])
O=np.array([0.2, 0.5, 1.51])

In [88]:
ox,oy,oz=O
c2=(ox**2+oy**2-d1**2-d2**2)/(2*d1*d2)
s2=np.sqrt(1-c2**2)
q2=Atan(s2,c2)

q1=Atan(ox,oy)+Atan(d1+d2*c2, d2*s2)

q4=q1+q2-Atan(R[1][0],R[0][0])
d3=-oz-d4

print("q1 =",q1)
print("q2 =",q2)
print("d3 =",d3)
print("q4 =",q4)

q1 = 0.653129120721679
q2 = 2.5963471663711646
d3 = -2.51
q4 = 3.2494762870928433


Testing the joint parameters using forwards kinematics.

In [89]:
n=4
dh=np.array([[q1, 0, d1, 0],
             [q2, 0, d2, np.pi],
             [0, d3, 0, 0],
             [q4, d4, 0, 0]])

A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])
ans=np.identity(4)

for i in range(n):
    ans=ans@A[i]
print("position of end effector:", ans[0:3,3])
print("orientation of end effector:")
print(ans[0:3,0:3])

position of end effector: [-0.2   0.5   1.51]
orientation of end effector:
[[ 1.00000000e+00  2.05498075e-16 -1.31863209e-17]
 [ 1.97671051e-16 -1.00000000e+00  1.21752695e-16]
 [-1.31863209e-17 -1.21752695e-16 -1.00000000e+00]]
