In [2]:
import numpy as np

In [38]:
n=int(input("Number of links: "))
dh=[0]*n
R_or_P=[0]*n

print("Link | theta_i | d_i | a_i | alpha_i")
for i in range(n):
    dh[i]=[eval(j) for j in input(str(i+1)+" "*6).split()]
    
lst=[int(i) for i in input("type the joint numbers of prismatic joints (leave empty if none): ").split()]
for i in lst:
    R_or_P[i-1]=1

Number of links: 3
Link | theta_i | d_i | a_i | alpha_i
1      0 1 0 -np.pi/2
2      np.pi/2 2 0 -np.pi/2
3      0 3 0 0
type the joint numbers of prismatic joints (leave empty if none): 1 2 3


In [39]:
A=[0]*n
for i in range(n):
    theta, d, a, alpha = dh[i]
    A[i]=np.array([[np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
                   [np.sin(theta), np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
                   [0, np.sin(alpha), np.cos(alpha), d],
                   [0, 0, 0, 1]])

In [40]:
ans=np.identity(4)
Z=[0]*(n+1)
Z[0]=np.array([[0],
               [0],
               [1]])

O=[0]*(n+1)
O[0]=np.array([0, 0, 0])

for i in range(n):
    ans=ans@A[i]
    Z[i+1]=ans[0:3, 0:3]@Z[0]
    O[i+1]=ans[0:3,3].T

In [41]:
J=[0]*n
for i in range(n):
    if R_or_P[i]==1:
        J[i]=np.concatenate((Z[i],np.array([[0,0,0]]).T),axis=0)
    else:
        cross=np.cross(Z[i].T,(O[n]-O[i]).T)
        J[i]=np.concatenate((cross.T,Z[i]),axis=0)

final_J=J[0]
for i in range(1,n):
    final_J=np.concatenate((final_J,J[i]),axis=1)

# print(final_J)
print(np.around(final_J,2))
Jv=final_J[0:3]

[[ 0.  0. -1.]
 [ 0.  1.  0.]
 [ 1.  0. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [43]:
#end-effector cartesian velocities
v=np.array([[1],
            [2],
            [3]])
join_params=np.linalg.pinv(Jv)@v
print(join_params)

[[ 3.]
 [ 2.]
 [-1.]]
